In [1]:
#ΤΟ ΘΕΛΩ ΠΑΝΤΟΤΕ
! pip install -U scikit-learn
#ΤΟ ΘΕΛΩ ΓΙΑ ΝΑ ΚΑΝΩ IMBALANCE ΤΟ DATASET ΜΟΥ
#! pip install -U imbalanced-learn

Requirement already up-to-date: scikit-learn in c:\users\user\anaconda3\lib\site-packages (0.22.2.post1)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn) (0.13.2)
Requirement already satisfied, skipping upgrade: numpy>=1.11.0 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn) (1.16.5)
Requirement already satisfied, skipping upgrade: scipy>=0.17.0 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn) (1.3.1)

WARNING: No metadata found in c:\users\user\anaconda3\lib\site-packages
WARNING: No metadata found in c:\users\user\anaconda3\lib\site-packages

In [2]:
#ΧΡΗΣΙΜΑ ΕΡΓΑΛΕΙΑ ΠΟΥ ΑΡΓΑ Η ΓΡΗΓΟΡΑ ΘΑ ΤΑ ΤΑ ΧΡΕΙΑΣΤΕΙΣ
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

#ΧΡΗΣΙΜΟ ΓΙΑ ΝΑ ΠΑΡΕΙΣ ΓΡΑΦΙΚΕΣ ΠΑΡΑΣΤΑΣΕΙΣ
import seaborn as sns

#ΕΡΓΑΛΕΙΑ ΓΙΑ ΝΑ ΚΑΝΕΙς IMPUTE TO DATASET ΣΟΥ ΔΗΛΑΔΗ ΝΑ ΓΕΜΊΣΕΙΣ ΜΕ ΤΙΜΕΣ ΤΑ NaN ΚΕΛΙΑ - ΛΕΙΤΟΥΡΓΕΙ ΓΙΑ ΑΡΙΘΜΗΤΙΚΕς ΤΙΜΕΣ
from sklearn.impute import SimpleImputer 
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

#ΓΙΑ ΝΑ ΚΑΝΕΙΣ LABEL ENCODER
from sklearn.preprocessing import LabelEncoder

#ΟΤΑΝ ΘΕΛΕΙΣ ΝΑ ΚΑΝΕΙΣ SPLIT ΤΟ DATASET ΣΟΥ ΣΕ TRAIN-TEST
from sklearn.model_selection import train_test_split

from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.feature_selection import VarianceThreshold
#from sklearn.preprocessing import LabelEncoder

#ΕΡΓΑΛΕΙΑ ΓΙΑ ΝΑ ΠΡΑΓΜΑΤΟΠΟΙΗΣΩ ΙΜΒΑLANCE - OVERSAMPLING - UNDERSAMPLING
from imblearn.over_sampling import RandomOverSampler
#from imblearn.under_sampling import RandomUnderSampler
#from imblearn.under_sampling import TomekLinks
#from imblearn.over_sampling import SMOTE #ΠΡΟΚΑΛΕΙ ΘΕΜΑΤΑ ΟΤΑΝ ΕΧΟΥΜΕ ΤΕΡΑΣΤΙΕΣ ΔΙΑΦΟΡΕΣ , ΧΡΗΣΙΜΟΠΟΙΕΙ KNN
#from imblearn.combine import SMOTETomek
#from imblearn.under_sampling import ClusterCentroids

Η διαδικασία που θα ακολουθήσουμε είναι η εξής :
* impute
* encode
* split
* standardization
* variance threshlod
* imbalance
* pca

In [3]:
abalone = pd.read_csv("datasets-master-57dcb67ef80b25c53c6e3b19a7f147d3c477446b/Abalone/abalone.data.csv",header=None)

In [4]:
abalone.head()

   0      1      2      3       4       5       6      7   8
0  M  0.455  0.365  0.095  0.5140  0.2245  0.1010  0.150  15
1  M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.070   7
2  F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.210   9
3  M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.155  10
4  I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.055   7

In [5]:
abalone.columns=['Sex','Lenght','Diameter','Height','Whole_Weight','Shucked_Weight','Viscera_Weight','Shell_Weight','Rings_Target']

In [6]:
abalone.head()

,Sex,Lenght,Diameter,Height,Whole_Weight,Shucked_Weight,Viscera_Weight,Shell_Weight,Rings_Target
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [7]:
def null_info(data):
    null_columns=data.columns[data.isnull().any()]
    print(data[data.isnull().any(axis=1)][null_columns])
    print(data.isnull().sum())
    print('Ποσοστο απουσιαζουσων τιμων ειναι=\n', data.isna().mean().round(4) * 100)

In [8]:
null_info(abalone)

Empty DataFrame
Columns: []
Index: []
Sex               0
Lenght            0
Diameter          0
Height            0
Whole_Weight      0
Shucked_Weight    0
Viscera_Weight    0
Shell_Weight      0
Rings_Target      0
dtype: int64
Ποσοστο απουσιαζουσων τιμων ειναι=
 Sex               0.0
Lenght            0.0
Diameter          0.0
Height            0.0
Whole_Weight      0.0
Shucked_Weight    0.0
Viscera_Weight    0.0
Shell_Weight      0.0
Rings_Target      0.0
dtype: float64

In [9]:
abalone.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
Sex               4177 non-null object
Lenght            4177 non-null float64
Diameter          4177 non-null float64
Height            4177 non-null float64
Whole_Weight      4177 non-null float64
Shucked_Weight    4177 non-null float64
Viscera_Weight    4177 non-null float64
Shell_Weight      4177 non-null float64
Rings_Target      4177 non-null int64
dtypes: float64(7), int64(1), object(1)
memory usage: 293.8+ KB

In [10]:
for j in abalone.columns:
    print(j,abalone[j].unique())

Sex ['M' 'F' 'I']
Lenght [0.455 0.35  0.53  0.44  0.33  0.425 0.545 0.475 0.55  0.525 0.43  0.49
 0.535 0.47  0.5   0.355 0.365 0.45  0.38  0.565 0.615 0.56  0.58  0.59
 0.605 0.575 0.68  0.665 0.705 0.465 0.54  0.24  0.205 0.21  0.39  0.46
 0.325 0.52  0.4   0.485 0.405 0.445 0.245 0.505 0.595 0.31  0.555 0.57
 0.6   0.62  0.625 0.695 0.36  0.51  0.435 0.495 0.385 0.515 0.37  0.27
 0.375 0.7   0.71  0.265 0.305 0.345 0.65  0.28  0.175 0.17  0.635 0.645
 0.61  0.725 0.235 0.315 0.225 0.64  0.63  0.585 0.42  0.335 0.415 0.275
 0.295 0.075 0.13  0.11  0.16  0.23  0.3   0.32  0.655 0.66  0.2   0.165
 0.19  0.74  0.34  0.675 0.745 0.685 0.69  0.67  0.29  0.26  0.395 0.41
 0.22  0.255 0.735 0.155 0.48  0.195 0.25  0.18  0.15  0.215 0.73  0.715
 0.765 0.185 0.285 0.72  0.75  0.755 0.78  0.815 0.14  0.77  0.775 0.76
 0.135 0.8  ]
Diameter [0.365 0.265 0.42  0.255 0.3   0.415 0.425 0.37  0.44  0.38  0.35  0.405
 0.355 0.4   0.28  0.34  0.295 0.32  0.275 0.48  0.45  0.445 0.475 0.47
 0.56  0.525 0.55  0.29  0.335 0.175 0.15  0.375 0.245 0.41  0.36  0.31
 0.385 0.19  0.345 0.325 0.495 0.39  0.235 0.51  0.465 0.535 0.435 0.43
 0.395 0.305 0.195 0.54  0.26  0.2   0.33  0.23  0.285 0.52  0.455 0.205
 0.13  0.5   0.515 0.485 0.46  0.545 0.57  0.575 0.16  0.21  0.49  0.25
 0.27  0.505 0.215 0.225 0.055 0.1   0.09  0.12  0.53  0.145 0.22  0.6
 0.58  0.585 0.565 0.555 0.185 0.165 0.125 0.59  0.14  0.11  0.155 0.315
 0.24  0.17  0.18  0.105 0.595 0.135 0.625 0.63  0.61  0.65  0.62  0.605
 0.095 0.115 0.615]
Height [0.095 0.09  0.135 0.125 0.08  0.15  0.14  0.11  0.145 0.1   0.13  0.085
 0.155 0.165 0.185 0.18  0.175 0.2   0.105 0.045 0.055 0.05  0.12  0.07
 0.16  0.06  0.17  0.195 0.19  0.115 0.075 0.065 0.215 0.21  0.23  0.205
 0.22  0.04  0.01  0.03  0.035 0.225 0.24  0.235 0.02  0.025 0.015 0.
 0.515 0.25  1.13 ]
Whole_Weight [0.514  0.2255 0.677  ... 1.176  1.0945 1.9485]
Shucked_Weight [0.2245 0.0995 0.2565 ... 0.727  0.137  0.9455]
Viscera_Weight [1.010e-01 4.850e-02 1.415e-01 1.140e-01 3.950e-02 7.750e-02 1.495e-01
 1.125e-01 1.510e-01 1.475e-01 8.100e-02 9.500e-02 1.710e-01 8.050e-02
 1.330e-01 8.700e-02 4.300e-02 7.500e-02 6.200e-02 4.900e-02 2.140e-01
 2.100e-01 3.010e-01 1.880e-01 2.720e-01 2.340e-01 2.190e-01 2.270e-01
 2.420e-01 2.805e-01 3.575e-01 3.925e-01 4.115e-01 1.240e-01 3.075e-01
 1.165e-01 2.035e-01 8.600e-02 9.100e-02 1.960e-01 2.350e-02 1.500e-02
 1.250e-02 4.500e-02 1.100e-01 2.550e-02 2.135e-01 1.110e-01 6.000e-02
 9.600e-02 1.055e-01 9.150e-02 1.755e-01 9.550e-02 1.200e-01 1.400e-02
 1.300e-01 1.600e-01 1.935e-01 8.000e-02 1.315e-01 1.015e-01 2.240e-01
 1.155e-01 4.050e-02 1.680e-01 9.850e-02 2.250e-01 2.610e-01 2.895e-01
 2.210e-01 1.890e-01 1.940e-01 1.595e-01 2.355e-01 2.520e-01 1.920e-01
 2.160e-01 2.225e-01 2.050e-01 2.075e-01 2.310e-01 1.675e-01 1.525e-01
 2.540e-01 3.180e-01 3.425e-01 3.880e-01 1.385e-01 1.320e-01 8.500e-02
 4.600e-02 1.915e-01 1.640e-01 2.405e-01 1.835e-01 1.830e-01 1.790e-01
 9.800e-02 1.345e-01 1.070e-01 6.350e-02 6.300e-02 1.460e-01 1.585e-01
 1.020e-01 1.720e-01 5.950e-02 1.035e-01 5.750e-02 1.725e-01 5.100e-02
 5.050e-02 5.450e-02 6.100e-02 2.635e-01 2.830e-01 3.600e-02 5.600e-02
 2.050e-02 3.450e-02 2.950e-02 2.055e-01 1.435e-01 3.060e-01 1.900e-01
 1.075e-01 1.080e-01 3.900e-02 6.500e-03 8.000e-03 2.620e-01 2.585e-01
 3.050e-01 1.310e-01 2.425e-01 2.615e-01 1.785e-01 2.475e-01 2.575e-01
 2.970e-01 3.980e-01 4.830e-01 4.515e-01 4.080e-01 3.085e-01 4.090e-01
 5.410e-01 1.690e-01 2.330e-01 1.845e-01 1.800e-02 3.700e-02 3.750e-02
 4.750e-02 2.165e-01 2.000e-01 2.660e-01 2.680e-01 3.670e-01 2.965e-01
 3.360e-01 3.315e-01 3.350e-01 2.710e-01 1.815e-01 1.965e-01 1.535e-01
 1.450e-01 1.780e-01 2.130e-01 1.465e-01 1.550e-01 7.100e-02 1.085e-01
 6.700e-02 1.685e-01 5.200e-02 1.625e-01 4.150e-02 7.850e-02 1.355e-01
 1.280e-01 1.635e-01 7.000e-02 1.150e-01 7.550e-02 1.235e-01 1.440e-01
 1.250e-01 8.200e-02 2.095e-01 1.580e-01 1.930e-01 2.870e-01 2.900e-02
 8.300e-02 3.200e-02 5.000e-04 3.000e-03 2.000e-03 4.500e-03 2.185e-01
 2.450e-02 1.050e-02 2.650e-02 3.250e-02 3.800e-02 3.500e-02 2.170e-01
 2.775e-01 2.065e-01 1.750e-01 1.655e-01 2.555e-01 2.390e-01 2.800e-02
 1.860e-01 8.850e-02 1.000e-01 2.855e-01 2.705e-01 2.505e-01 3.335e-01
 1.970e-01 3.270e-01 2.450e-01 3.345e-01 3.115e-01 1.605e-01 5.700e-02
 1.040e-01 1.270e-01 1.325e-01 8.150e-02 1.795e-01 2.260e-01 2.790e-01
 2.205e-01 2.070e-01 3.400e-02 2.850e-02 1.275e-01 5.850e-02 8.950e-02
 1.740e-01 4.950e-02 9.500e-03 5.000e-03 3.690e-01 3.055e-01 2.045e-01
 3.235e-01 2.700e-01 2.945e-01 2.200e-02 4.100e-02 5.300e-02 1.665e-01
 4.000e-02 1.610e-01 5.650e-02 4.200e-02 4.085e-01 3.175e-01 2.655e-01
 2.760e-01 3.250e-01 2.275e-01 2.565e-01 3.065e-01 1.520e-01 1.730e-01
 5.550e-02 7.400e-02 2.455e-01 2.905e-01 2.590e-01 2.860e-01 4.900e-01
 3.885e-01 4.720e-01 3.920e-01 2.460e-01 2.995e-01 3.015e-01 2.440e-01
 2.735e-01 2.765e-01 2.990e-01 3.455e-01 3.265e-01 4.530e-01 3.140e-01
 2.920e-01 3.695e-01 3.365e-01 2.875e-01 3.135e-01 1.370e-01 1.220e-01
 1.245e-01 1.225e-01 1.190e-01 5.350e-02 6.400e-02 1.760e-01 1.390e-01
 1.985e-01 1.045e-01 1.820e-01 2.215e-01 2.115e-01 2.385e-01 1.715e-01
 2.465e-01 2.670e-01 3.490e-01 1.990e-01 3.580e-01 1.230e-01 2.000e-02
 2.030e-01 2.435e-01 1.735e-01 1.290e-01 1.705e-01 1.560e-01 9.050e-02
 4.350e-02 5.500e-02 6.450e-02 1.380e-01 5.250e-02 7.700e-02 1.360e-01
 1.575e-01 2.320e-01 1.590e-01 4.725e-01 3.540e-01 2.195e-01 3.045e-01
 1.200e-02 3.500e-03 3.035e-01 2.665e-01 1.405e-01 1.455e-01 1.395e-01
 3.405e-01 3.215e-01 2.445e-01 1.765e-01 2.120e-01 2.370e-01 1.615e-01
 1.810e-01 2.235e-01 2.595e-01 2.090e-01 2.315e-01 2.020e-01 2.145e-01
 2.560e-01 2.305e-01 2.470e-01 1.570e-01 2.040e-01 1.265e-01 3.650e-02
 2.150e-02 1.950e-02 5.900e-02 8.500e-03 3.850e-02 4.450e-02 6.000e-03
 2.550e-01 6.600e-02 9.250e-02 6.950e-02 5.500e-03 1.555e-01 2.005e-01
 1.950e-01 1.410e-01 2.980e-01 2.625e-01 9.200e-02 1.630e-01 1.260e-01
 1.005e-01 1.090e-01 8.750e-02 2.010e-01 1.975e-01 2.495e-01 3.435e-01
 6.500e-02 1.620e-01 1.905e-01 7.600e-02 5.800e-02 2.975e-01 1.530e-01
 1.825e-01 2.255e-01 2.245e-01 1.135e-01 7.950e-02 4.550e-02 1.130e-01
 6.750e-02 8.250e-02 3.550e-02 7.050e-02 4.700e-02 3.350e-02 4.250e-02
 1.095e-01 1.160e-01 1.850e-01 9.450e-02 1.065e-01 5.400e-02 1.365e-01
 8.400e-02 1.050e-01 9.900e-02 2.400e-02 4.650e-02 3.445e-01 6.150e-02
 6.650e-02 1.400e-01 2.430e-01 1.430e-01 1.480e-01 2.600e-02 9.400e-02
 2.325e-01 2.125e-01 1.425e-01 6.550e-02 2.500e-03 1.145e-01 6.850e-02
 1.420e-01 1.030e-01 9.000e-02 2.750e-02 1.900e-02 1.150e-02 4.000e-03
 2.280e-01 1.195e-01 2.015e-01 1.695e-01 1.805e-01 2.175e-01 1.945e-01
 4.805e-01 4.105e-01 1.500e-01 3.005e-01 3.680e-01 2.360e-01 1.670e-01
 3.610e-01 2.960e-01 5.000e-02 2.395e-01 2.815e-01 1.700e-01 1.505e-01
 1.375e-01 2.060e-01 1.650e-02 2.025e-01 1.285e-01 2.600e-01 1.170e-01
 9.350e-02 3.000e-02 2.100e-02 4.800e-02 1.185e-01 1.855e-01 2.400e-01
 2.155e-01 3.300e-01 2.605e-01 2.750e-01 2.545e-01 2.850e-01 2.755e-01
 3.320e-01 3.150e-01 2.910e-01 3.415e-01 3.910e-01 3.220e-01 3.775e-01
 4.220e-01 4.190e-01 1.350e-02 2.500e-02 3.100e-02 3.050e-02 4.400e-02
 6.900e-02 7.450e-02 7.200e-02 7.800e-02 8.350e-02 9.300e-02 8.550e-02
 1.060e-01 1.215e-01 1.295e-01 1.205e-01 1.340e-01 2.290e-01 2.745e-01
 2.200e-01 2.645e-01 2.580e-01 2.780e-01 3.020e-01 2.840e-01 2.480e-01
 3.000e-01 3.260e-01 3.420e-01 3.555e-01 3.080e-01 3.120e-01 3.225e-01
 3.310e-01 3.025e-01 3.595e-01 2.940e-01 3.145e-01 3.615e-01 3.620e-01
 4.015e-01 3.960e-01 4.200e-01 5.225e-01 4.185e-01 3.830e-01 4.400e-01
 5.090e-01 7.500e-03 9.000e-03 1.300e-02 1.550e-02 1.750e-02 2.700e-02
 8.650e-02 7.350e-02 1.120e-01 1.490e-01 1.775e-01 1.885e-01 2.375e-01
 1.910e-01 4.260e-01 2.570e-01 2.365e-01 2.500e-01 2.715e-01 2.900e-01
 2.110e-01 3.390e-01 3.725e-01 3.655e-01 3.685e-01 3.105e-01 4.050e-01
 3.485e-01 3.715e-01 3.355e-01 4.180e-01 3.070e-01 3.810e-01 4.070e-01
 3.130e-01 4.800e-01 4.690e-01 4.255e-01 3.800e-01 5.500e-01 4.585e-01
 5.195e-01 5.130e-01 4.985e-01 3.300e-02 6.250e-02 6.050e-02 7.150e-02
 8.900e-02 7.300e-02 1.255e-01 1.210e-01 1.350e-01 1.445e-01 1.545e-01
 1.650e-01 1.305e-01 1.840e-01 2.525e-01 1.470e-01 2.730e-01 2.535e-01
 2.345e-01 1.745e-01 2.335e-01 1.955e-01 3.195e-01 2.685e-01 3.450e-01
 2.950e-01 1.865e-01 2.725e-01 2.695e-01 3.720e-01 3.515e-01 2.740e-01
 3.780e-01 3.585e-01 3.735e-01 3.865e-01 3.525e-01 3.125e-01 4.870e-01
 4.160e-01 3.990e-01 3.740e-01 4.865e-01 4.195e-01 3.890e-01 5.640e-01
 4.345e-01 4.600e-01 4.460e-01 5.190e-01 1.450e-02 9.950e-02 1.105e-01
 1.025e-01 1.565e-01 2.180e-01 2.300e-01 2.150e-01 2.085e-01 2.350e-01
 3.245e-01 3.650e-01 3.040e-01 4.095e-01 3.510e-01 3.240e-01 4.475e-01
 3.255e-01 3.325e-01 3.665e-01 3.630e-01 4.130e-01 4.270e-01 3.970e-01
 1.100e-02 1.700e-02 3.150e-02 1.175e-01 1.485e-01 1.870e-01 1.660e-01
 2.380e-01 1.980e-01 1.515e-01 1.925e-01 2.410e-01 2.265e-01 2.640e-01
 2.515e-01 2.915e-01 2.230e-01 2.865e-01 3.090e-01 2.925e-01 4.205e-01
 2.880e-01 3.370e-01 2.810e-01 3.805e-01 2.690e-01 3.295e-01 3.545e-01
 3.845e-01 2.530e-01 3.200e-01 3.110e-01 3.095e-01 3.305e-01 2.930e-01
 3.750e-01 3.675e-01 3.935e-01 4.565e-01 4.925e-01 4.540e-01 3.660e-01
 4.425e-01 4.030e-01 5.185e-01 4.825e-01 4.210e-01 6.415e-01 7.600e-01
 2.295e-01 2.785e-01 3.330e-01 4.360e-01 4.265e-01 9.650e-02 9.750e-02
 1.335e-01 1.645e-01 2.285e-01 2.885e-01 2.825e-01 3.460e-01 4.405e-01
 3.465e-01 3.840e-01 2.485e-01 3.030e-01 2.955e-01 2.675e-01 2.845e-01
 3.790e-01 4.020e-01 3.835e-01 4.470e-01 2.985e-01 3.470e-01 3.605e-01
 4.305e-01 4.915e-01 1.850e-02 2.300e-02 6.800e-02 1.540e-01 1.770e-01
 3.530e-01 2.250e-02 1.895e-01 3.395e-01 3.870e-01 3.975e-01 4.480e-01
 4.755e-01 2.650e-01 2.105e-01 3.705e-01 1.000e-02 7.250e-02 2.770e-01
 7.650e-02 8.450e-02 4.370e-01 3.285e-01 4.650e-01 4.920e-01 4.075e-01
 3.600e-01 3.765e-01 2.835e-01 3.480e-01 5.900e-01 1.875e-01 4.350e-01
 4.230e-01 2.080e-01 3.430e-01 1.180e-01 1.800e-01 3.710e-01 1.115e-01
 2.630e-01 3.230e-01 3.170e-01 3.755e-01 4.290e-01 3.855e-01 4.420e-01
 5.005e-01 5.120e-01 4.820e-01 1.995e-01 3.520e-01 5.265e-01 5.235e-01
 8.800e-02 9.700e-02 4.365e-01 2.220e-01 2.820e-01 3.770e-01 3.375e-01
 3.730e-01 4.170e-01 3.210e-01 5.250e-01 1.600e-02 3.155e-01 2.890e-01
 4.630e-01 5.115e-01 5.150e-02 3.190e-01 4.055e-01 4.655e-01 4.780e-01
 4.740e-01 3.905e-01 4.035e-01 3.165e-01 3.340e-01 4.285e-01 4.575e-01
 3.565e-01 3.795e-01 3.570e-01 7.000e-03 4.065e-01 3.985e-01 3.205e-01
 3.280e-01 4.005e-01 4.395e-01 2.800e-01 2.415e-01 4.875e-01 7.900e-02
 4.505e-01 3.410e-01 5.750e-01 3.850e-01 3.645e-01 3.965e-01 3.275e-01
 4.435e-01 4.010e-01 3.505e-01 5.145e-01 2.795e-01 4.100e-01 3.940e-01
 5.745e-01 4.025e-01 4.215e-01 4.695e-01 3.950e-01 3.385e-01 3.860e-01
 3.500e-01 4.665e-01 3.820e-01 4.045e-01 4.110e-01 2.490e-01 3.640e-01
 4.385e-01 3.535e-01 4.225e-01 2.935e-01 5.260e-01]
Shell_Weight [0.15   0.07   0.21   0.155  0.055  0.12   0.33   0.26   0.165  0.32
 0.135  0.19   0.205  0.185  0.24   0.115  0.13   0.1    0.075  0.085
 0.27   0.2    0.305  0.3    0.285  0.28   0.295  0.46   0.35   0.455
 0.49   0.125  0.34   0.145  0.09   0.02   0.012  0.015  0.14   0.045
 0.245  0.16   0.11   0.22   0.17   0.025  0.175  0.485  0.275  0.425
 0.38   0.315  0.345  0.675  0.58   0.36   0.44   0.4    0.255  0.39
 0.48   0.25   0.335  0.235  0.105  0.18   0.31   0.03   0.08   0.54
 0.78   0.41   0.129  0.062  0.068  0.028  0.1355 0.048  0.063  0.117
 0.0925 0.2475 0.2665 0.4465 0.2425 0.174  0.1565 0.042  0.0125 0.01
 0.325  0.45   0.355  0.635  1.005  0.815  0.725  0.85   0.65   0.76
 0.62   0.59   0.035  0.05   0.57   0.29   0.195  0.465  0.23   0.06
 0.435  0.04   0.0015 0.004  0.003  0.005  0.37   0.365  0.026  0.0905
 0.55   0.385  0.585  0.69   0.43   0.225  0.375  0.074  0.0715 0.011
 0.535  0.265  0.065  0.095  0.71   0.395  0.7    0.445  0.47   0.415
 0.5    0.6    0.42   0.605  0.215  0.505  0.0995 0.008  0.625  0.2185
 0.177  0.1045 0.181  0.2765 0.2645 0.1345 0.475  0.179  0.0325 0.0885
 0.131  0.1135 0.049  0.027  0.0155 0.1175 0.168  0.096  0.0345 0.0985
 0.1275 0.515  0.0835 0.0865 0.166  0.2235 0.154  0.059  0.136  0.081
 0.1515 0.169  0.1655 0.148  0.152  0.044  0.0195 0.054  0.1335 0.1405
 0.158  0.53   0.1195 0.0875 0.173  0.123  0.1105 0.144  0.0795 0.0765
 0.1005 0.032  0.083  0.0335 0.0695 0.0245 0.0085 0.293  0.4405 0.525
 0.233  0.278  0.2965 0.2905 0.1845 0.262  0.1635 0.263  0.1685 0.1625
 0.256  0.3635 0.234  0.214  0.122  0.2885 0.018  0.023  0.0535 0.0575
 0.0745 0.0735 0.0615 0.0605 0.086  0.082  0.077  0.094  0.106  0.109
 0.091  0.0945 0.1465 0.089  0.172  0.1525 0.1775 0.239  0.202  0.2375
 0.283  0.2875 0.2385 0.2745 0.194  0.2705 0.3095 0.271  0.3205 0.3445
 0.3985 0.292  0.3685 0.411  0.381  0.406  0.2715 0.321  0.399  0.405
 0.601  0.453  0.413  0.897  0.0135 0.021  0.017  0.0385 0.043  0.037
 0.0425 0.0445 0.067  0.1125 0.1145 0.134  0.137  0.119  0.1295 0.1265
 0.113  0.143  0.1095 0.146  0.127  0.1575 0.1695 0.1495 0.1535 0.1825
 0.1785 0.156  0.1885 0.1955 0.186  0.2155 0.2195 0.218  0.274  0.343
 0.249  0.276  0.2835 0.237  0.309  0.2515 0.2925 0.3085 0.3295 0.388
 0.349  0.401  0.3235 0.3745 0.409  0.3185 0.432  0.336  0.3725 0.477
 0.403  0.441  0.5175 0.4005 0.553  0.498  0.503  0.4045 0.5475 0.4135
 0.6205 0.0095 0.007  0.0215 0.0225 0.034  0.039  0.0405 0.0635 0.087
 0.093  0.1035 0.088  0.1315 0.0975 0.098  0.102  0.142  0.1665 0.141
 0.1585 0.182  0.1385 0.157  0.167  0.254  0.1835 0.201  0.1895 0.223
 0.2165 0.2215 0.206  0.224  0.2575 0.222  0.238  0.228  0.253  0.2295
 0.2565 0.317  0.357  0.2415 0.2865 0.267  0.2405 0.281  0.332  0.286
 0.287  0.3425 0.358  0.3735 0.4245 0.294  0.364  0.476  0.3595 0.353
 0.4735 0.3865 0.3695 0.4375 0.446  0.638  0.3995 0.301  0.4525 0.5075
 0.5375 0.5215 0.2685 0.4505 0.4825 0.545  0.6785 0.595  0.586  0.0355
 0.038  0.052  0.0435 0.0525 0.064  0.058  0.061  0.0755 0.0775 0.0655
 0.126  0.1245 0.114  0.1505 0.132  0.2065 0.196  0.171  0.1905 0.164
 0.2045 0.192  0.189  0.2075 0.2175 0.229  0.227  0.207  0.2545 0.248
 0.2325 0.236  0.2695 0.219  0.2655 0.2125 0.306  0.2955 0.204  0.2255
 0.269  0.3035 0.347  0.2895 0.354  0.3045 0.3365 0.3455 0.323  0.3665
 0.4075 0.4325 0.391  0.383  0.3925 0.3575 0.469  0.461  0.4975 0.512
 0.528  0.51   0.5365 0.52   0.565  0.558  0.612  0.7975 0.036  0.053
 0.0675 0.0825 0.0855 0.0815 0.0805 0.073  0.103  0.1075 0.1015 0.1025
 0.1065 0.116  0.1365 0.1165 0.147  0.198  0.1555 0.161  0.149  0.1735
 0.203  0.1945 0.3055 0.2095 0.2335 0.288  0.3315 0.251  0.312  0.3465
 0.329  0.3245 0.377  0.4025 0.495  0.3195 0.444  0.4195 0.4685 0.494
 0.5015 0.013  0.0415 0.066  0.076  0.0955 0.0965 0.1205 0.112  0.1935
 0.162  0.138  0.178  0.2135 0.213  0.1725 0.259  0.217  0.231  0.2815
 0.268  0.2285 0.2535 0.2725 0.2635 0.3345 0.431  0.266  0.2945 0.379
 0.311  0.313  0.3325 0.3105 0.3145 0.3705 0.339  0.328  0.3615 0.418
 0.4435 0.386  0.3845 0.378  0.363  0.341  0.308  0.4275 0.3545 0.3965
 0.4125 0.4705 0.438  0.502  0.566  0.511  0.5655 0.557  0.482  0.575
 0.63   0.642  0.578  0.0705 0.1675 0.1645 0.211  0.1215 0.209  0.2365
 0.319  0.2825 0.296  0.273  0.252  0.159  0.2105 0.1795 0.304  0.2845
 0.344  0.2485 0.4155 0.258  0.3285 0.297  0.3005 0.3475 0.291  0.3075
 0.466  0.389  0.4215 0.4645 0.4425 0.643  0.009  0.1185 0.191  0.184
 0.1425 0.183  0.1875 0.244  0.279  0.246  0.277  0.2265 0.2795 0.242
 0.264  0.298  0.352  0.2985 0.3225 0.3885 0.5195 0.3215 0.361  0.3535
 0.289  0.3395 0.412  0.3255 0.4675 0.3385 0.474  0.3305 0.3645 0.497
 0.394  0.348  0.436  0.416  0.4115 0.4715 0.384  0.538  0.4395 0.501
 0.488  0.646  0.006  0.041  0.0495 0.046  0.078  0.1375 0.2035 0.1765
 0.2675 0.2625 0.0285 0.033  0.057  0.0725 0.121  0.139  0.1455 0.2605
 0.356  0.3375 0.372  0.462  0.479  0.602  0.4935 0.6585 0.885  0.0035
 0.5855 0.0935 0.665  0.61   0.685  0.216  0.66   0.1815 0.0075 0.069
 0.1475 0.555  0.022  0.2115 0.3065 0.187  0.163  0.199  0.3175 0.471
 0.513  0.4065 0.4535 0.6095 0.016  0.0255 0.031  0.0365 0.047  0.111
 0.1305 0.118  0.1325 0.107  0.1225 0.1485 0.2505 0.3275 0.3165 0.3775
 0.4175 0.5165 0.624  0.5335 0.584  0.0315 0.1605 0.1755 0.2245 0.491
 0.2345 0.327  0.176  0.3755 0.351  0.3935 0.5085 0.5285 0.0105 0.101
 0.1155 0.2305 0.1615 0.1805 0.2435 0.2785 0.3265 0.367  0.272  0.307
 0.324  0.3115 0.346  0.422  0.4865 0.404  0.056  0.0585 0.1115 0.1985
 0.1965 0.2595 0.337  0.3485 0.4105 0.299  0.331  0.371  0.4755 0.3875
 0.4945 0.5315 0.0455 0.072  0.1545 0.2525 0.2055 0.208  0.3135 0.3605
 0.2775 0.398  0.2915 0.2615 0.3525 0.387  0.5305 0.097  0.1975 0.322
 0.326  0.437  0.563  0.726  0.084  0.079  0.2315 0.4695 0.3825 0.3155
 0.3015 0.3355 0.3415 0.4485 0.4055 0.4625 0.5965 0.0595 0.188  0.221
 0.439  0.421  0.0895 0.316  0.3815 0.0185 0.0065 0.6855 0.396  0.3805
 0.193  0.1595 0.0485 0.212  0.104  0.2495 0.0915 0.5235 0.0645 0.151
 0.1915 0.4265 0.529  0.014  0.128  0.4085 0.449  0.468  0.0305 0.0505
 0.0625 0.1855 0.2445 0.374  0.302  0.369  0.6195 0.1395 0.333  0.3905
 0.4305 0.5675 0.029  0.1745 0.2225 0.247  0.3555 0.2935 0.284  0.4355
 0.4165 0.4895 0.434  0.6745 0.0465 0.1255 0.2455 0.4095 0.407  0.516
 0.1435 0.2735 0.314  0.342  0.456  0.5295 0.153  0.3945 0.4575 0.4285
 0.56   0.1085 0.655  0.019  0.133  0.496  0.547  0.5055 0.5755 0.621
 0.3505 0.2015 0.4295 0.4545 0.499  0.1415 0.2755 0.3855 0.506  0.5385
 0.3795 0.2585 0.424  0.508  0.657  0.092 ]
Rings_Target [15  7  9 10  8 20 16 19 14 11 12 18 13  5  4  6 21 17 22  1  3 26 23 29
  2 27 25 24]

In [11]:
#ONE HOT ENCODING ΓΙΑ ΤΙΣ ΣΤΗΛΕΣ ΠΟΥ ΒΛΕΠΟΥΜΕ ΟΤΙ ΜΑΣ ΕΝΟΧΛΟΥΝ
abalone_data=pd.get_dummies(abalone,columns=['Sex'])

In [12]:
#ΤΟΠΟΘΕΤΟΥΜΕ ΤΗΝ ΣΤΗΛΗ Τarget ΣΤΟ ΤΕΛΟΣ ΓΙΑΤΙ ΜΑΣ ΕΞΥΠΗΡΕΤΕΙ
cols = list(abalone_data.columns.values) 
cols.pop(cols.index('Rings_Target')) 
abalone_data = abalone_data[cols+['Rings_Target']]

In [13]:
abalone_data.head()

,Lenght,Diameter,Height,Whole_Weight,Shucked_Weight,Viscera_Weight,Shell_Weight,Sex_F,Sex_I,Sex_M,Rings_Target
0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,0,0,1,15
1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,0,0,1,7
2,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,1,0,0,9
3,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,0,0,1,10
4,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,0,1,0,7

In [14]:
abalone_data.shape

(4177, 11)

In [15]:
abalone_features_df=abalone_data.iloc[:,:10]
abalone_labels_df=abalone_data.iloc[:,[10]]

In [16]:
abalone_train, abalone_test, abalone_train_labels, abalone_test_labels = train_test_split(abalone_features_df, abalone_labels_df, test_size=0.2,random_state=1)
abalone_train.index = range(len(abalone_train))
abalone_test.index =range(len(abalone_test))
abalone_train_labels.index = range(len(abalone_train_labels))
abalone_test_labels.index = range(len(abalone_test_labels))

In [17]:
def scaled_Standard(train,test):
    cols1=train.columns
    cols2=test.columns
    scaler = preprocessing.StandardScaler().fit(train)
    train_scaled = scaler.transform(train)
    test_scaled = scaler.transform(test)
    train_scaled=pd.DataFrame(data=train_scaled,columns=cols1)
    test_scaled=pd.DataFrame(data=test_scaled,columns=cols2)
    return train_scaled,test_scaled

In [18]:
abalone_train_sca,abalone_test_sca=scaled_Standard(abalone_train,abalone_test)

In [19]:
abalone_train.head()

,Lenght,Diameter,Height,Whole_Weight,Shucked_Weight,Viscera_Weight,Shell_Weight,Sex_F,Sex_I,Sex_M
0,0.455,0.350,0.120,0.4835,0.1815,0.1440,0.160,0,0,1
1,0.255,0.195,0.055,0.0725,0.0285,0.0170,0.021,0,1,0
2,0.520,0.410,0.110,0.5185,0.2165,0.0915,0.184,0,1,0
3,0.620,0.470,0.155,0.9660,0.4470,0.1710,0.284,0,1,0
4,0.615,0.490,0.155,0.9885,0.4145,0.1950,0.345,0,1,0

In [20]:
abalone_train_sca.head()

,Lenght,Diameter,Height,Whole_Weight,Shucked_Weight,Viscera_Weight,Shell_Weight,Sex_F,Sex_I,Sex_M
0,-0.568635,-0.579140,-0.457631,-0.703506,-0.799739,-0.332330,-0.565851,-0.67558,-0.690188,1.321943
1,-2.226410,-2.133887,-1.974904,-1.538022,-1.489042,-1.491966,-1.555788,-0.67558,1.448882,-0.756462
2,-0.029858,0.022697,-0.691057,-0.632440,-0.642055,-0.811707,-0.394926,-0.67558,1.448882,-0.756462
3,0.799029,0.624535,0.359362,0.276187,0.396405,-0.085793,0.317259,-0.67558,1.448882,-0.756462
4,0.757585,0.825147,0.359362,0.321872,0.249985,0.133350,0.751692,-0.67558,1.448882,-0.756462

In [21]:
def variance(train,test,thresh):
    cols1=train.columns
    cols2=test.columns
    variance_thresh = VarianceThreshold(thresh)
    x_train = variance_thresh.fit_transform(train)
    x_test = variance_thresh.transform(test)
    x_train=pd.DataFrame(data=x_train)#,columns=cols1)
    x_test=pd.DataFrame(data=x_test)#,columns=cols2)
    return x_train, x_test

In [22]:
abalone_train_sca_var,abalone_test_sca_var=variance(abalone_train_sca,abalone_test,0.2)

In [23]:
abalone_train_sca_var.head()

,0,1,2,3,4,5,6,7,8,9
0,-0.568635,-0.579140,-0.457631,-0.703506,-0.799739,-0.332330,-0.565851,-0.67558,-0.690188,1.321943
1,-2.226410,-2.133887,-1.974904,-1.538022,-1.489042,-1.491966,-1.555788,-0.67558,1.448882,-0.756462
2,-0.029858,0.022697,-0.691057,-0.632440,-0.642055,-0.811707,-0.394926,-0.67558,1.448882,-0.756462
3,0.799029,0.624535,0.359362,0.276187,0.396405,-0.085793,0.317259,-0.67558,1.448882,-0.756462
4,0.757585,0.825147,0.359362,0.321872,0.249985,0.133350,0.751692,-0.67558,1.448882,-0.756462

In [24]:
abalone_train_labels.nunique()

Rings_Target    27
dtype: int64

In [25]:
print('Max variable=',abalone_train_labels['Rings_Target'].value_counts().idxmax(),'with frequency=',abalone_train_labels['Rings_Target'].value_counts().max())
print('Min variable=',abalone_train_labels['Rings_Target'].value_counts().idxmin(),'with frequency=',abalone_train_labels['Rings_Target'].value_counts().min())
print('ratio=',abalone_train_labels['Rings_Target'].value_counts().min()*100/abalone_train_labels['Rings_Target'].value_counts().max())

Max variable= 9 with frequency= 557
Min variable= 26 with frequency= 1
ratio= 0.17953321364452424

In [26]:
abalone_train_labels.apply(pd.value_counts)

    Rings_Target
9            557
10           491
8            461
11           396
7            311
6            206
12           204
13           164
14           102
5             95
15            82
16            57
4             46
17            46
18            32
19            25
20            22
3             13
21            11
23             7
22             5
24             2
27             2
26             1
1              1
25             1
29             1

In [27]:
#Random undersampling deletes examples from the majority class
def randomoversampler(train,train_labels):
    cols1=train.columns
    cols2=train_labels.columns
    ros = RandomOverSampler()
    X_ros, y_ros = ros.fit_sample(train, train_labels)
    X_ros=pd.DataFrame(data=X_ros,columns=cols1)
    y_ros=pd.DataFrame(data=y_ros,columns=cols2)
    return X_ros, y_ros

In [28]:
abalone_train_sca_var,abalone_train_labels=randomoversampler(abalone_train_sca_var,abalone_train_labels)

In [29]:
abalone_train_labels.apply(pd.value_counts)

    Rings_Target
23           557
19           557
16           557
24           557
1            557
9            557
17           557
25           557
10           557
18           557
26           557
3            557
11           557
27           557
15           557
4            557
12           557
20           557
5            557
13           557
21           557
29           557
6            557
14           557
22           557
7            557
8            557

In [30]:
def pca(n,train,test):
    cols1=train.columns
    cols2=test.columns
    pcaa = PCA(n_components=n)
    trainPCA =  pcaa.fit_transform(train)
    testPCA = pcaa.transform(test)
    trainPCA=pd.DataFrame(data=trainPCA)#,columns=cols1)
    testPCA=pd.DataFrame(data=testPCA)#,columns=cols2)
    return trainPCA , testPCA

In [31]:
final_train,final_test=pca(10,abalone_train_sca_var,abalone_test_sca_var)

In [32]:
final_train=final_train
final_test=final_test
final_train_labels=abalone_train_labels
final_test_labels=abalone_test_labels

In [33]:
final_train.shape

(15039, 10)

In [34]:
final_train_labels.shape

(15039, 1)

In [35]:
final_test.shape

(836, 10)

In [36]:
final_test_labels.shape

(836, 1)